import {ArrowDownRight,ArrowUpRight,Github,Linkedin,Mail} from 'lucide-react';

const projects=[
{n:'01',type:'Deep Learning',title:'Clothing Image Classification',desc:'A compact CNN trained from scratch to classify clothing images across five categories.',meta:'PyTorch · CNN · Python',stat:'92.33% test accuracy',url:'https://github.com/pc-mt/clothing-image-classification-cnn',featured:true},
{n:'02',type:'Software Engineering',title:'Quiz Arena',desc:'A real-time multiplayer quiz platform connecting web players, ESP32 controllers and a reactive Java backend.',meta:'Java · Vert.x · MQTT · ESP32 · Docker',stat:'Real-time multiplayer',url:'https://github.com/pc-mt/quiz-arena',featured:true},
{n:'03',type:'Data Science',title:'Retail Sales Forecasting',desc:'End-to-end retail analytics combining data-quality engineering, XGBoost forecasting and store segmentation.',meta:'KNIME · XGBoost · k-means',stat:'92,592 training observations',url:'https://github.com/pc-mt/retail-sales-forecasting-knime',featured:true},
{n:'04',type:'Machine Learning',title:'Fraud Detection',desc:'A model comparison exploring why accuracy alone can mislead on imbalanced fraud data.',meta:'Decision Tree · Random Forest · KNIME',stat:'23 / 221 frauds detected',url:'#',featured:false},
{n:'05',type:'Software Engineering',title:'DMTree Community',desc:'Full-stack community platform with authentication, discussions, voting, comments and role-based features.',meta:'Java · Vert.x · MariaDB · JWT · Docker',stat:'Full-stack platform',url:'https://github.com/pc-mt/projekt-forum-platform',featured:false},
{n:'06',type:'Learning Project',title:'Python Task Manager',desc:'A command-line task manager built while developing core Python and application-structure skills.',meta:'Python · CLI',stat:'Learning project',url:'https://github.com/pc-mt/task-manager',featured:false},
];

function App(){
return <div className="site">
<header><a className="brand" href="#">Priscille.</a><nav><a href="#about">About</a><a href="#work">Projects</a><a href="#experience">Experience</a><a href="#contact">Contact</a></nav><div className="right"><span className="langs">EN <i/> DE <i/> FR</span><a aria-label="GitHub" href="https://github.com/pc-mt" target="_blank"><Github size={17}/></a><a aria-label="LinkedIn" href="https://www.linkedin.com/in/priscille-moumani-43506b350/" target="_blank"><Linkedin size={17}/></a></div></header>
<main>
<section className="hero"><div className="eyebrow">Computer Science · Gießen, Germany</div><h1>Software meets<br/><em>data.</em></h1><p className="lead">I build thoughtful software and data-driven solutions — from full-stack systems to machine learning models.</p><div className="actions"><a className="primary" href="#work">View my work <ArrowDownRight size={18}/></a><a className="textlink" href="#contact">Get in touch <ArrowUpRight size={16}/></a></div><div className="availability"><span/>Open to student opportunities</div></section>
<section id="about" className="about"><div className="section-label">01 — About</div><div className="about-copy"><h2>Building with curiosity,<br/>learning with purpose.</h2><p>I'm a Computer Science student at Technische Hochschule Mittelhessen, working at the intersection of software engineering and data science. I enjoy turning technical problems into clear, useful solutions.</p><p className="muted">My work ranges from reactive Java backends and connected hardware to machine learning pipelines and deep learning models.</p></div></section>
<section id="work" className="work"><div className="section-head"><div><div className="section-label">02 — Selected work</div><h2>Projects with<br/><em>substance.</em></h2></div><p>A selection of academic and personal work across software engineering, data science and machine learning.</p></div>
<div className="projects">{projects.map((p,i)=><article className={p.featured?'project featured':'project'} key={p.n}><div className="project-num">{p.n}</div><div className="project-body"><span className="project-type">{p.type}</span><h3>{p.title}</h3><p>{p.desc}</p><div className="project-meta">{p.meta}</div></div><div className="project-side"><span>{p.stat}</span>{p.url!=='#'?<a href={p.url} target="_blank" aria-label={'Open '+p.title}><ArrowUpRight/></a>:<span className="soon">Case study soon</span>}</div></article>)}</div></section>
<section id="experience" className="education"><div className="section-label">03 — Education</div><div className="edu-row"><div><span>2023 — 2027</span><h3>B.Sc. Computer Science</h3><p>Technische Hochschule Mittelhessen</p></div><div className="courses"><span>Selected coursework</span><p>Data Science <b>1.0</b> · Database Systems <b>1.3</b><br/>Software Engineering <b>2.0</b> · Deep Learning <b>2.4</b></p></div></div></section>
<section id="contact" className="contact"><div className="section-label">04 — Contact</div><h2>Let's build something<br/><em>meaningful.</em></h2><p>Interested in my work or want to talk about an opportunity?</p><a className="primary" href="mailto:PLACEHOLDER_EMAIL">Say hello <Mail size={17}/></a></section>
</main>
<footer><span>© 2026 Priscille Moumani</span><span>Designed & built with care.</span><a href="#">Back to top ↑</a></footer>
</div>}
export default App;